language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  include:
    - php: 5.3
      dist: precise
      
before_install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
       composer require satooshi/php-coveralls:dev-master
    fi

install:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
       composer update
    else
       composer install
    fi

cache:
  directories:
    - $HOME/.composer/cache

script: 
  - ./vendor/bin/phpunit --coverage-clover=clover.xml src/

after_script:
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.6" ]]; then
       php ./vendor/bin/coveralls -v
    fi